<h1>Fetching Data From an API</h1>

In [2]:
import pandas as pd
import requests

<h1>Loading the data from API</h1>

In [3]:
response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=833e1ff3b6f680d67ab5b33c4b35e9e2&language=en-US&page=1')

<h1>Converting the data into dataframe from json</h1>

In [4]:
response.json() #the json file has the data as a dictionary and all the data we need is assigned to the key "results", so we will only fetch that key.

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg',
   'genre_ids': [28, 18, 80],
   'id': 1439930,
   'title': 'The Punisher: One Last Kill',
   'original_language': 'en',
   'original_title': 'The Punisher: One Last Kill',
   'overview': 'As Frank Castle searches for meaning beyond revenge, an unexpected force pulls him back into the fight.',
   'popularity': 631.4432,
   'poster_path': '/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg',
   'release_date': '2026-05-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.488,
   'vote_count': 970},
  {'adult': False,
   'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 417.1089,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 3690},
  {'adult': False,
   'backdrop_path': '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
   'genre_ids': [10751, 35, 12, 14, 16],
   'id': 1226863,
   'title': 'The Super Mario Galaxy Movie',
   'original_language': 'en',
   'original_title': 'The Super Mario Galaxy Movie',
   'overview': "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
   'popularity': 332.9093,
   'poster_path': '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
   'release_date': '2026-04-01',
   'softcore': False,
   'video': False,
   'vote_average': 7.195,
   'vote_count': 1109},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [16, 10751, 12, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 325.0364,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.981,
   'vote_count': 1207},
  {'adult': False,
   'backdrop_path': '/wMrV8SLne1jHLeYS0lLrA1Tf86P.jpg',
   'genre_ids': [27, 9648],
   'id': 1304313,
   'title': "Lee Cronin's The Mummy",
   'original_language': 'en',
   'original_title': "Lee Cronin's The Mummy",
   'overview': 'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
   'popularity': 303.3424,
   'poster_path': '/1q308iixueCU4pFtSYugNOevtNx.jpg',
   'release_date': '2026-04-15',
   'softcore': False,
   'video': False,
   'vote_average': 7.703,
   'vote_count': 497},
  {'adult': False,
   'backdrop_path': '/gkh6Nt8DtY1XT4gQsyFq9XAVJlJ.jpg',
   'genre_ids': [18, 35],
   'id': 350,
   'title': 'The Devil Wears Prada',
   'original_language': 'en',
   'original_title': 'The Devil Wears Prada',
   'overview': 'A young woman from the Midwest gets more than she bargained for when she moves to New York to become a writer and ends up as the assistant to the tyrannical, larger-than-life editor-in-chief of a major fashion magazine.',
   'popularity': 257.6913,
   'poster_path': '/8912AsVuS7Sj915apArUFbv6F9L.jpg',
   'release_date': '2006-06-29',
   'softcore': False,
   'video': False,
   'vote_average': 7.416,
   'vote_count': 13490},
  {'adult': False,
   'backdrop_path': '/1x9e0qWonw634NhIsRdvnneeqvN.jpg',
   'genre_ids': [10749, 18],
   'id': 1523145,
   'title': 'Your Heart Will Be Broken',
   'original_language': 'ru',
   'original_title': 'Твоё сердце будет разбито',
   'overview': 'High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.',
   'popularity': 220.0597,
   'poster_path': '/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg',
   'release_date': '2026-03-26',
   'softcore': False,
   'video': False,
   'vote_average': 6.776,
   'vote_count': 78},
  {'adult': False,
   'backdrop_path': '/oTE4lNs4PSG5iIWjqaTdCIFJ4Bs.jpg',
   'genre_ids': [28, 53],
   'id': 1318447,
   'title': 'Apex',
   'original_language': 'en',
   'original_title': 'Apex',
   'overview': "A grieving woman pushing her limits on a solo adventure in the Australian wild is ensnared in a twisted game with a cunning killer who thinks she's prey.",
   'popularity': 208.8431,
   'poster_path': '/eTp7gSPkSF3Aw79mNx1NkBP1PZT.jpg',
   'release_date': '2026-04-24',
   'softcore': False,
   'video': False,
   'vote_average': 6.667,
   'vote_count': 1118},
  {'adult': False,
   'backdrop_path': '/5AsIFZ2AJC7JcGpq40aRPuRuaRc.jpg',
   'genre_ids': [18],
   'id': 1241752,
   'title': 'Rita',
   'original_language': 'tl',
   'original_title': 'Rita',
   'overview': 'Rita, who finds herself alone when husband Ariel works abroad. They both find solace and sexual satisfaction in other people. When Ariel comes back, they both act like nothing happened. But will this keep their marriage from falling apart?',
   'popularity': 179.8232,
   'poster_path': '/pXENxAzOBrTSDJGxDcUnlNTNmWr.jpg',
   'release_date': '2024-03-22',
   'softcore': False,
   'video': False,
   'vote_average': 6.217,
   'vote_count': 23},
  {'adult': False,
   'backdrop_path': '/6ELCZlTA5lGUops70hKdB83WJxH.jpg',
   'genre_ids': [28, 14, 12],
   'id': 460465,
   'title': 'Mortal Kombat',
   'original_language': 'en',
   'original_title': 'Mortal Kombat',
   'overview': "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
   'popularity': 159.5253,
   'poster_path': '/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg',
   'release_date': '2021-04-07',
   'softcore': False,
   'video': False,
   'vote_average': 7.0,
   'vote_count': 6570},
  {'adult': False,
   'backdrop_path': '/3ryYzE3WPCfFObyJNN1wVU54HaX.jpg',
   'genre_ids': [27],
   'id': 1339713,
   'title': 'Obsession',
   'original_language': 'en',
   'original_title': 'Obsession',
   'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
   'popularity': 159.0266,
   'poster_path': '/40I66L7QKguTFDPvcLcdiTbAD7I.jpg',
   'release_date': '2026-04-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.0,
   'vote_count': 133},
  {'adult': False,
   'backdrop_path': '/4EAAwpylq313qrDqpCxulUrXBNF.jpg',
   'genre_ids': [28, 14, 12],
   'id': 931285,
   'title': 'Mortal Kombat II',
   'original_language': 'en',
   'original_title': 'Mortal Kombat II',
   'overview': 'The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.',
   'popularity': 156.8035,
   'poster_path': '/lIsMeDbwntNXSUVHmWMMRXEZOVc.jpg',
   'release_date': '2026-05-06',
   'softcore': False,
   'video': False,
   'vote_average': 6.9,
   'vote_count': 226},
  {'adult': False,
   'backdrop_path': '/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg',
   'genre_ids': [878, 12, 14],
   'id': 83533,
   'title': 'Avatar: Fire and Ash',
   'original_language': 'en',
   'original_title': 'Avatar: Fire and Ash',
   'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
   'popularity': 153.3,
   'poster_path': '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg',
   'release_date': '2025-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 7.5,
   'vote_count': 3102},
  {'adult': False,
   'backdrop_path': '/xA6AM5MvEkieZKlv1Tn3sN23I7i.jpg',
   'genre_ids': [28, 18, 10749],
   'id': 1630423,
   'title': 'My Dearest Assassin',
   'original_language': 'th',
   'original_title': 'เลือดรัก นักฆ่า',
   'overview': 'Hunted for her rare blood type, a caged woman vows to fight alongside the assassin she loves to protect their future when an old enemy resurfaces.',
   'popularity': 143.1011,
   'poster_path': '/ul4dQcA68mtSx8J56N5gEcaCCtP.jpg',
   'release_date': '2026-05-06',
   'softcore': False,
   'video': False,
   'vote_average': 8.614,
   'vote_count': 180},
  {'adult': False,
   'backdrop_path': '/hdLsZ3dCjKt5A6xDpoo3UFgcTSm.jpg',
   'genre_ids': [27, 28],
   'id': 1426822,
   'title': 'Mortal Game',
   'original_language': 'en',
   'original_title': 'Mortal Game',
   'overview': 'A group of hunters travel to a mysterious island to track down a legendary forest creature. They soon realize their guide has set them up as bait, forcing them to confront a highly intelligent predator that terrorizes them one by one.',
   'popularity': 139.2287,
   'poster_path': '/iCvucorbs3hFqWshDbLe0fHzB71.jpg',
   'release_date': '2025-02-03',
   'softcore': False,
   'video': False,
   'vote_average': 4.571,
   'vote_count': 7},
  {'adult': False,
   'backdrop_path': '/jAJYVbVR5fP0BeTQXRP1BXjW5bl.jpg',
   'genre_ids': [18],
   'id': 1669050,
   'title': 'Tayuan 2',
   'original_language': 'tl',
   'original_title': 'Tayuan 2',
   'overview': 'A charming bus conductor drawn to both men and women who feels an unexpected spark with a shy commuter. On crowded bus rides where bodies brush, desire grows and love becomes messy.',
   'popularity': 138.4844,
   'poster_path': '/gkHNa8q3RNhgj2EMuoYWJUHsMa6.jpg',
   'release_date': '2026-04-17',
   'softcore': False,
   'video': False,
   'vote_average': 4.667,
   'vote_count': 6},
  {'adult': False,
   'backdrop_path': '/hlZGaey4lR9hc4rGxZRAmIEsZOc.jpg',
   'genre_ids': [28, 18],
   'id': 1292415,
   'title': 'Beast',
   'original_language': 'en',
   'original_title': 'Beast',
   'overview': 'MMA legend Patton James, now a commercial fisherman, is pulled back into the cage when his brother is in danger. Reuniting with his old coach Sammy, he commits to one final fight in one championship against the brutal champion Xavier Grau.',
   'popularity': 136.2291,
   'poster_path': '/7NrvUI3vnW8H3rD7ExKcTL7KRcQ.jpg',
   'release_date': '2026-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 6.359,
   'vote_count': 32},
  {'adult': False,
   'backdrop_path': '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
   'genre_ids': [12, 16, 35, 10751, 878],
   'id': 1327819,
   'title': 'Hoppers',
   'original_language': 'en',
   'original_title': 'Hoppers',
   'overview': "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.",
   'popularity': 133.6249,
   'poster_path': '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
   'release_date': '2026-03-04',
   'softcore': False,
   'video': False,
   'vote_average': 8.1,
   'vote_count': 1137},
  {'adult': False,
   'backdrop_path': '/9dMp9t0d0nIGhiil8TyqChwiNwA.jpg',
   'genre_ids': [53, 27, 35],
   'id': 1266127,
   'title': 'Ready or Not: Here I Come',
   'original_language': 'en',
   'original_title': 'Ready or Not: Here I Come',
   'overview': 'Moments after surviving an all-out attack from the Le Domas family, Grace discovers she’s reached the next level of the nightmarish game — and this time with her estranged sister Faith at her side. Grace has one chance to survive, keep her sister alive, and claim the High Seat of the Council that controls the world. Four rival families are hunting her for the throne, and whoever wins rules it all.',
   'popularity': 127.504,
   'poster_path': '/13ZcJzSGEqVgDSqsS9U5EkQwPkV.jpg',
   'release_date': '2026-03-19',
   'softcore': False,
   'video': False,
   'vote_average': 7.653,
   'vote_count': 776},
  {'adult': False,
   'backdrop_path': '/8qkDwjTFoLAwmYh2J9HMeIDRlxd.jpg',
   'genre_ids': [18, 9648],
   'id': 249397,
   'title': 'Nymphomaniac: Vol. II',
   'original_language': 'en',
   'original_title': 'Nymphomaniac: Vol. II',
   'overview': "The continuation of Joe's sexually dictated life delves into the darker aspects of her adult life and what led to her being in Seligman's care.",
   'popularity': 113.6926,
   'poster_path': '/iLUNqgNKuWn667kXCKztSxYbT3k.jpg',
   'release_date': '2013-12-25',
   'softcore': False,
   'video': False,
   'vote_average': 6.709,
   'vote_count': 3151}],
 'total_pages': 56935,
 'total_results': 1138686}

In [5]:
pd.DataFrame(response.json()['results']).head() #converted into DataFrame

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg,"[28, 18, 80]",1439930,The Punisher: One Last Kill,en,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,631.4432,/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg,2026-05-12,False,False,8.488,970
1,False,/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,417.1089,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.600,3690
2,False,/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg,"[10751, 35, 12, 14, 16]",1226863,The Super Mario Galaxy Movie,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,332.9093,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,False,False,7.195,1109
3,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[16, 10751, 12, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",325.0364,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.981,1207
4,False,/wMrV8SLne1jHLeYS0lLrA1Tf86P.jpg,"[27, 9648]",1304313,Lee Cronin's The Mummy,en,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,303.3424,/1q308iixueCU4pFtSYugNOevtNx.jpg,2026-04-15,False,False,7.703,497

<p>Now we can manipulate the data and use only those cols that are needed</p>

<h2>However this was for only 1 page and the whole dataset has 56848 pages, so we have to run a loop to merge the whole dataset, however i wont run the code as it will take long time to complete the loop for that many pages</h2>

In [6]:
df=pd.DataFrame()

In [7]:
for i in range(1,501):
    response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=833e1ff3b6f680d67ab5b33c4b35e9e2&language=en-US&page={}'.format(i))
    temp_df=pd.DataFrame(response.json()['results']).head()
    df=pd.concat([df,temp_df],ignore_index=True)

<p>This appends the head from every page to the newly created DataFrame "df".

Here I am only using 500 pages as the data is too big</p>

In [10]:
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg,"[28, 18, 80]",1439930,The Punisher: One Last Kill,en,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,631.4432,/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg,2026-05-12,False,False,8.488,970
1,False,/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,417.1089,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.600,3690
2,False,/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg,"[10751, 35, 12, 14, 16]",1226863,The Super Mario Galaxy Movie,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,332.9093,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,False,False,7.195,1109
3,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[16, 10751, 12, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",325.0364,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.981,1207
4,False,/wMrV8SLne1jHLeYS0lLrA1Tf86P.jpg,"[27, 9648]",1304313,Lee Cronin's The Mummy,en,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,303.3424,/1q308iixueCU4pFtSYugNOevtNx.jpg,2026-04-15,False,False,7.703,497
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,False,/7Bp3zLFUNTvEapUMyshBpd5fnxm.jpg,"[16, 28, 878, 35]",765172,Rise of the Teenage Mutant Ninja Turtles: The ...,en,Rise of the Teenage Mutant Ninja Turtles: The ...,When a mysterious stranger arrives from the fu...,2.2492,/rSmTqtb7gICeRwvsEmq0uJxR4XU.jpg,2022-11-19,False,False,7.176,108
2496,False,/A2kXYkGGdeLU20YHPM9qs6GX9nN.jpg,"[27, 9648]",11026,Exorcist: The Beginning,en,Exorcist: The Beginning,Years before Father Merrin helped save Regan M...,2.2492,/4b7Mhc4HZN7XzMMLukaQ9C0x1Dx.jpg,2004-08-20,False,False,5.402,884
2497,False,/djdmfIB2ePyWBhebelAk2ls4Rz3.jpg,"[28, 80, 53]",40025,Black Ransom,cn,撕票風雲,"A powerful triad boss has been kidnapped, and ...",2.2487,/7MJBg0lrNIO0IVwTBswLxgO10Mh.jpg,2010-01-07,False,False,6.024,41
2498,False,/7TIoq6DRnMn2aDViSRfPooWZkga.jpg,"[28, 18, 53]",1289601,Life After Fighting,en,Life After Fighting,Retired martial arts world champion Alex Faulk...,2.2486,/wcf965PrbcIjFO6n3IIrSv09thh.jpg,2024-06-07,False,False,7.217,76
2499,False,/u70yZonRQy8WOURASeTmxhKWDIT.jpg,"[35, 10749]",11137,The Prince & Me,en,The Prince & Me,A fairy tale love-story about pre-med student ...,2.2485,/2voUK98TW1cJ3w0qmDIdB16A3x6.jpg,2004-03-28,False,False,6.211,1041

<h1>Converting the dataframe into a CSV file</h1>

In [11]:
df.to_csv('movies.csv')