In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

<h1>Working with Dates</h1>

In [6]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

<h3>1. Extract year</h3>

In [8]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
969 2019-11-28        1307        1       9       2019
786 2018-08-21         888       20       6       2018
226 2018-10-31        4036       13       1       2018
110 2019-08-13        7059       14      11       2019
186 2019-05-30        4992        9      15       2019

<h3>2. Extract Month</h3>

In [9]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [10]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

<h3>3. Extract Days</h3>

In [11]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [12]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [13]:
# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [14]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

<h3>4. Extract Quarter</h3>

In [16]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

<h3>5. Extract Semester</h3>

In [17]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

<h3>6. Extract Time elapsed between dates</h3>

In [18]:
import datetime
today=datetime.datetime.today()

In [19]:
today

datetime.datetime(2026, 5, 27, 2, 32, 29, 822215)

In [23]:
#time passed
today - date['date']

0     2360 days 02:32:29.822215
1     2842 days 02:32:29.822215
2     2773 days 02:32:29.822215
3     2475 days 02:32:29.822215
4     2698 days 02:32:29.822215
                 ...
995   2788 days 02:32:29.822215
996   2729 days 02:32:29.822215
997   2577 days 02:32:29.822215
998   2642 days 02:32:29.822215
999   2416 days 02:32:29.822215
Name: date, Length: 1000, dtype: timedelta64[ns]

In [24]:
#days passed
(today - date['date']).dt.days

0      2360
1      2842
2      2773
3      2475
4      2698
       ...
995    2788
996    2729
997    2577
998    2642
999    2416
Name: date, Length: 1000, dtype: int64

In [31]:
# Months passed

np.round((today -date['date']).dt.days/30,0)

0      79.0
1      95.0
2      92.0
3      82.0
4      90.0
       ...
995    93.0
996    91.0
997    86.0
998    88.0
999    81.0
Name: date, Length: 1000, dtype: float64

<h1>Working with Time</h1>

In [26]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [28]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

<h3>Extract Time part</h3>

In [29]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

<h3>Time Difference</h3>

In [30]:
today-time['date']

0     4546 days 01:42:29.822215
1     4410 days 02:52:29.822215
2     4896 days 02:11:29.822215
3     4198 days 02:01:29.822215
4     4595 days 03:21:29.822215
                 ...
995   5185 days 01:42:29.822215
996   4506 days 03:18:29.822215
997   4971 days 02:55:29.822215
998   5087 days 02:58:29.822215
999   4359 days 03:07:29.822215
Name: date, Length: 1000, dtype: timedelta64[ns]

In [38]:
#in seconds
np.round((today-time['date']).dt.total_seconds())

0      392780550.0
1      381034350.0
2      423022290.0
3      362714490.0
4      397020090.0
          ...
995    447990150.0
996    389330310.0
997    429504930.0
998    439527510.0
999    376628850.0
Name: date, Length: 1000, dtype: float64

In [39]:
#in minutes
np.round((today-time['date']).dt.total_seconds()/60)

0      6546342.0
1      6350572.0
2      7050371.0
3      6045241.0
4      6617001.0
         ...
995    7466502.0
996    6488838.0
997    7158415.0
998    7325458.0
999    6277147.0
Name: date, Length: 1000, dtype: float64

In [40]:
#in hours
np.round((today-time['date']).dt.total_seconds()/3600)

0      109106.0
1      105843.0
2      117506.0
3      100754.0
4      110283.0
         ...
995    124442.0
996    108147.0
997    119307.0
998    122091.0
999    104619.0
Name: date, Length: 1000, dtype: float64